package com.philip.keynote.ui.theme

object Localization {
    private val indonesian = mapOf(
        "app_name" to "KeyNote",
        "notes" to "Catatan",
        "trash" to "Tong Sampah",
        "archive" to "Arsip Catatan",
        "settings" to "Pengaturan",
        "sync_backup" to "Sinkronisasi & Backup",
        "empty_notes" to "Belum ada catatan. Klik + untuk membuat baru.\n(Seret ke atas untuk melihat Arsip)",
        "empty_trash" to "Tong sampah kosong.",
        "empty_archive" to "Arsip kosong. Seret ke bawah untuk kembali.",
        "test_biometric" to "Uji Autentikasi Biometrik",
        "insert_encrypted" to "Masukkan Catatan Uji Coba Terenkripsi",
        "password_manager" to "Password Manager",
        "folders" to "Kelompok Akun Terenkripsi",
        "add_category" to "Tambah Kategori Baru",
        "category_name" to "Nama Kategori",
        "add" to "Tambah",
        "cancel" to "Batal",
        "no_category" to "Belum ada kategori.",
        "no_accounts" to "Belum ada akun di kategori ini.",
        "search" to "Cari...",
        "language" to "Bahasa",
        "theme" to "Tema",
        "view_mode" to "Tampilan Utama",
        "notebook_lines" to "Garis Buku",
        "font_size" to "Ukuran Font",
        "font_style" to "Gaya Font",
        "text_align" to "Rata Teks",
        "font_color" to "Warna Font",
        "save" to "Simpan",
        "delete" to "Hapus",
        "restore" to "Pulihkan",
        "delete_forever" to "Hapus Selamanya",
        "original_notes" to "Kembalikan ke Catatan Utama",
        "setup_master_pin" to "Buat PIN Master Baru",
        "setup_master_pin_desc" to "PIN ini akan melindungi pengelola kata sandi terenkripsi Anda.",
        "enter_pin" to "Masukkan 4-Digit PIN",
        "confirm_pin" to "Konfirmasi PIN",
        "save_continue" to "Simpan & Lanjutkan"
    )

    private val english = mapOf(
        "app_name" to "KeyNote",
        "notes" to "Notes",
        "trash" to "Trash",
        "archive" to "Archive",
        "settings" to "Settings",
        "sync_backup" to "Sync & Backup",
        "empty_notes" to "No notes yet. Tap + to create one.\n(Swipe up to open Archive)",
        "empty_trash" to "Trash is empty.",
        "empty_archive" to "Archive is empty. Swipe down to go back.",
        "test_biometric" to "Test Biometric Authentication",
        "insert_encrypted" to "Insert Encrypted Test Note",
        "password_manager" to "Password Manager",
        "folders" to "Encrypted Accounts Group",
        "add_category" to "Add New Category",
        "category_name" to "Category Name",
        "add" to "Add",
        "cancel" to "Cancel",
        "no_category" to "No categories yet.",
        "no_accounts" to "No accounts in this category.",
        "search" to "Search...",
        "language" to "Language",
        "theme" to "Theme",
        "view_mode" to "View Mode",
        "notebook_lines" to "Notebook Lines",
        "font_size" to "Font Size",
        "font_style" to "Font Style",
        "text_align" to "Text Alignment",
        "font_color" to "Font Color",
        "save" to "Save",
        "delete" to "Delete",
        "restore" to "Restore",
        "delete_forever" to "Delete Forever",
        "original_notes" to "Restore to Main Notes",
        "setup_master_pin" to "Create New Master PIN",
        "setup_master_pin_desc" to "This PIN will protect your encrypted password manager.",
        "enter_pin" to "Enter 4-Digit PIN",
        "confirm_pin" to "Confirm PIN",
        "save_continue" to "Save & Continue"
    )

    fun getString(key: String, lang: String): String {
        val dict = if (lang == "en") english else indonesian
        return dict[key] ?: key
    }
}
